<?php if(isset($mensaje)){?>

<div class="tab-content" style="width:98%;">
          <div id="usuario" class="tab-pane fade in active">
            <h3>Mensajes</h3>
            <p>Busque por:</p>
            <div class="row busqueUsuario" id="inputBusqueda">
                <div class="col-md-12">
					<input class="form-control buscar" id="busque-nombre"  type="text" />
                </div>
            </div>

            <div class="row">&nbsp;</div>
            <div class="row">
              <div class="col-md-12">
                  <div class="panel panel-default panel-table">
					
                    <div class="panel-heading">
                      <div class="row">
                        <div class="col col-xs-6">
                          <h3 class="panel-title">Listado Mensajes</h3>
                        </div>
						<div class="col col-xs-6 text-right">
                          <a href="<?=APP_PAGE_OMOLDS;?>publico/agregarAlBuzon"  class="btn btn-sm btn-primary btn-create amarillo" target="buzonUrl" >url Buzon </a>
                        </div>
					 </div>	
                    </div>
                    <div class="panel-body table-responsive">
                      <table class="table table-striped table-bordered table-list">
                        <thead>
                          <tr>
							<th>Fecha</th>
                            <th>Mensaje</th>
                            <th><em class="fa fa-cog"></em></th>
                          </tr> 
                        </thead>
							<tbody id="myTable">
								<?php $totalMensaje = 0;?>
								 <?php foreach($mensaje as $campos): ?>
								  <tr>
									<td><?=($campos->fecha); ?></td>
									<td><?=($campos->mensaje); ?>
										<?php $totalMensaje ++;?>
									</td>
									<td>
										  <a class="btn btn-info" href="#"  data-toggle="modal" data-target="#modalVer-<?=$campos->id; ?>"><i class="fa fa-eye" aria-hidden="true"></i></a>
										  <a class="btn btn-danger" href="#"  data-toggle="modal" data-target="#modalEliminar-<?=$campos->id; ?>"><i class="fa fa-trash-o" aria-hidden="true"></i></a>
									  </td>
								  </tr>
								 <?php endforeach; ?> 
                               

                              </tbody>
                      </table>
                    </div>
                    <div class="panel-footer">
                      <div class="row">
                        
                        <div class="col col-xs-4">Total de mensajes <span style="color:#CC004D;">OM</span> (<span style="color:#CC004D;"><?= $totalMensaje ?></span>) 
                        </div>
                        <div class="col col-xs-8">
                          <ul class="pagination hidden-xs pull-right" id="myPager">
                          </ul>
                          <ul class="pagination visible-xs pull-right">
                              <li><a href="#">«</a></li>
                              <li><a href="#">»</a></li>
                          </ul>
                        </div>
                      </div>
                    </div>
                  </div>
              </div>
            </div>
          </div>
</div>

<?php foreach($mensaje as $campos): ?>

			 <!-- Modal Ver-->
	         <div id="modalVer-<?=$campos->id; ?>" class="modal fade" role="dialog">
		    <div class="modal-dialog"  style="width:50%;">
		      <!-- Modal content-->
		      <div class="modal-content">
		        <div class="modal-header">
		          <button type="button" class="close" data-dismiss="modal">&times;</button>
		          <h4 class="modal-title"><?= ($campos->Fecha); ?></h4>
		        </div>

				<div class="modal-body">
				  <div class="row">

					
						<div class="col-md-12">
						  <div class="form-group row margin">
								<label for="example-text-input" class="col-2 col-form-label">Fecha:</label>
								<label for="example-text-input" class="col-2 col-form-label"><b><?=($campos->Fecha); ?></b></label>
								<br>
								
								<label for="example-text-input" class="col-2 col-form-label">Mensaje:</label>
								<label for="example-text-input" class="col-2 col-form-label"><b><?=($campos->mensaje); ?></b></label>
								<br>
						  </div>
						</div>
			
				</div>
	
			  </div>
					
		        
		      </div>
		    </div>
			
		  </div>
	        
	         <!-- Modal de borrar-->
	        <form id="eliminar-alert" method="post" action="<?=APP_PAGE_OMOLDS;?>inicio/eliminaBuzon" class="contact-form form" target="resDelete<?=$campos->id; ?>">
	        <div id="modalEliminar-<?=$campos->id; ?>" class="modal fade" role="dialog">
	          <div class="modal-dialog" style="width:60%;">
	            <!-- Modal content-->
	            <div class="modal-content">
	              <div class="modal-header">
	                <button type="button" class="close" data-dismiss="modal">&times;</button>
	                <h4 class="modal-title">Borrar <?= ($campos->Fecha); ?></h4>
	              </div>
	              <div class="modal-body">
	               	<p>Estas seguro de eliminar el mensaje</p>
	              </div>
	              <div class="modal-footer">
					<input type="hidden" name="idCampo" id="idCampo" value="<?=$campos->id; ?>" required="required" class="form-control">
					<input type="hidden"  name="idUsuario" required="required" class="form-control" value="<?= $idUsuario ?>">
					<div class="row">
						<div class="col-md-8">
							<div class="col-md-8 col-md-offset-2 col-sm-12">
							<iframe name="resDelete<?=$campos->id; ?>" src="<?=APP_PAGE_OMOLDS;?>inicio/eliminaBuzon" style="height: auto; max-width: 100%; width: 100%;" frameborder="0"></iframe>
						   </div>
						</div>
						<div class="col-md-4">
							<div class="col-md-6"><button type="submit" class="btn btn-default">Borrar</button></div>
							<div class="col-md-6"><button type="button" class="btn btn-sm btn-primary btn-create amarillo" data-dismiss="modal">Cancelar</button></div>
						</div>
					</div>
	                
	              </div>
	            </div>
	          </div>
	        </div>
	        </form>
<?php endforeach; ?>
<?php } ?>


<style>
.margin{
	margin-left : 5px;
	margin-right : 5px;
}
</style>

<script>
	function actualizarIframe() {
		$("#dataclientes")[0].src = $("#dataclientes")[0].src;   
	}
</script>

 <script>
	$( function() {
		$("#myTable").makeSearchList();
	});
	jQuery.fn.makeSearchList = function() { 	
			input = $('.buscar');	
			$(input).attr("placeholder","Search here ...");	
			var list	= $(this);
			$(input)
			.change( function () {
					var filter = $(this).val();	        
					if(filter) {	        	
					$("tr",$(list)).hide();
					  $("tr:Contains(" + filter + ")",$(list)).show();
					} else {	        	
						$("tr",$(list)).show();
					}
					return false;
				  })
				.keyup( function () {	        
					$(this).change();
				});	  
		 
				// Creamos la pseudo-funcion Contains
				jQuery.expr[":"].Contains = jQuery.expr.createPseudo(function(arg) {
					return function( elem ) {
						return jQuery(elem).text().toUpperCase().indexOf(arg.toUpperCase()) >= 0;
					};
				});
		 
		};
		
</script>
  
