<?php if(isset($instructores)){?>

<div class="tab-content" style="width:98%;">
          <div id="usuario" class="tab-pane fade in active">
            <h3>Instructores</h3>
            <p>Busque por:</p>
            <div class="row busqueUsuario" id="inputBusqueda">
                <div class="col-md-6">
					 <label for="example-text-input" class="col-2 col-form-label">Nombre:</label>
					<input class="form-control buscar" id="busque-nombre"  type="text" />
                </div>
                <div class="col-md-6">
					<label for="example-text-input" class="col-2 col-form-label">Cédula:</label>
                  <input class="form-control buscar" id="busque-cedula" type="number" />
                </div>
            </div>

            <div class="row">&nbsp;</div>
            <div class="row">
              <div class="col-md-12">
                  <div class="panel panel-default panel-table">
                    <div class="panel-heading">
                      <div class="row">
                        <div class="col col-xs-6">
                          <h3 class="panel-title">Listado instructores</h3>
                        </div>
                        <div class="col col-xs-6 text-right">
                          <button type="button" class="btn btn-sm btn-primary btn-create amarillo" data-toggle="modal" data-target="#nuevoUsuario">Nuevo ++</button>
                        </div>
                      </div>
                    </div>
                    <div class="panel-body table-responsive">
                      <table class="table table-striped table-bordered table-list">
                        <thead>
                          <tr>
							<th>Nombre</th>
                            <th>Celular</th>
                            <th>Correo electrónico</th>
                            <th>Tipo</th>
                            <th><em class="fa fa-cog"></em></th>
                          </tr> 
                        </thead>
							<tbody id="myTable">
								<?php $totalProductos = 0;?>
								 <?php foreach($instructores as $campos): ?>
								  <tr>
									<td><?=($campos->nombre); ?></td>
									<td><?=($campos->celular); ?></td>
									<td><?=($campos->email); ?></td>
									<td><?=($campos->tipo); ?>
										<?php $totalProductos ++;?>
									</td>
									<td><?=($campos->activo); ?></td>
										 <td>
										  <a class="btn btn-info" href="#"  data-toggle="modal" data-target="#modalVer-<?=$campos->id; ?>"><i class="fa fa-eye" aria-hidden="true"></i></a>
										  <a class="btn btn-primary" href="#"  data-toggle="modal" data-target="#modalEditar-<?=$campos->id; ?>"><i class="fa fa-pencil" aria-hidden="true"></i></a>
										  <a class="btn btn-danger" href="#"  data-toggle="modal" data-target="#modalEliminar-<?=$campos->id; ?>"><i class="fa fa-trash-o" aria-hidden="true"></i></a>
									  </td>
								  </tr>
								 <?php endforeach; ?> 
                               

                              </tbody>
                      </table>
                    </div>
                    <div class="panel-footer">
                      <div class="row">
                        
                        <div class="col col-xs-4">Total de instrutores <span style="color:#CC004D;">OM</span> (<span style="color:#CC004D;"><?= $totalProductos ?></span>) 
                        </div>
                        <div class="col col-xs-8">
                          <ul class="pagination hidden-xs pull-right" id="myPager">
                          </ul>
                          <ul class="pagination visible-xs pull-right">
                              <li><a href="#">«</a></li>
                              <li><a href="#">»</a></li>
                          </ul>
                        </div>
                      </div>
                    </div>
                  </div>
              </div>
            </div>
          </div>
</div>

<?php foreach($instructores as $campos): ?>

			 <!-- Modal Ver-->
	         <div id="modalVer-<?=$campos->id; ?>" class="modal fade" role="dialog">
		    <div class="modal-dialog"  style="width:50%;">
		      <!-- Modal content-->
		      <div class="modal-content">
		        <div class="modal-header">
		          <button type="button" class="close" data-dismiss="modal">&times;</button>
		          <h4 class="modal-title"><?= ($campos->nombre); ?></h4>
		        </div>

				<div class="modal-body">
				  <div class="row">

					
						<div class="col-md-12">
						  <div class="form-group row margin">
								<label for="example-text-input" class="col-2 col-form-label">Nombre:</label>
								<label for="example-text-input" class="col-2 col-form-label"><b><?=($campos->nombre); ?></b></label>
								<br>
								
								<label for="example-text-input" class="col-2 col-form-label">Correo Electrónico:</label>
								<label for="example-text-input" class="col-2 col-form-label"><b><?=($campos->email); ?></b></label>
								<br>
								
								<label for="example-text-input" class="col-2 col-form-label">Tipo de Instructor:</label>
								<label for="example-text-input" class="col-2 col-form-label"><b><?=($campos->tipo); ?></b></label>
								<br>	
								
								<label for="example-text-input" class="col-2 col-form-label">Celular:</label>
								<label for="example-text-input" class="col-2 col-form-label"><b><?=($campos->celular); ?></b></label>
								<br>
						  </div>
						</div>
			
				</div>
	
			  </div>
					
		        
		      </div>
		    </div>
			
		  </div>
	       
			
	        <!-- Modal Editar-->
	        <form id="edit-alert" method="post" action="<?=APP_PAGE_OMOLDS;?>inicio/editarInstructor" class="contact-form form" target="resUpdate<?=$campos->id; ?>">
	        <div id="modalEditar-<?=$campos->id; ?>" class="modal fade" role="dialog">
		    <div class="modal-dialog"  style="width:80%;">
		      <!-- Modal content-->
		      <div class="modal-content">
		        <div class="modal-header">
		          <button type="button" class="close" data-dismiss="modal">&times;</button>
		          <h4 class="modal-title"><?= ($campos->nombre); ?></h4>
		        </div>

				<div class="modal-body">
					<div class="row">
					
						<div class="col-md-6">
						  <div class="form-group row margin">
								<label for="example-text-input" class="col-2 col-form-label">Nombre:</label>
								<div class="col-10">
									<input id="nombre" name="nombre"  value="<?=($campos->nombre); ?>" type="text" min="3" class="form-control" data-validation="required" required>
								</div>
								
								<label for="example-text-input" class="col-2 col-form-label">Correo Electrónico:</label>
									<div class="col-10">
										<input id="email" name="email"   value="<?=($campos->email); ?>" type="email" min="3" class="form-control" data-validation="required email" required>
								</div>
								
								<label for="example-text-input" class="col-2 col-form-label">Tipo de Instructor:</label>
									<div class="col-10">
										<input id="tipo" name="tipo"  value="<?=($campos->tipo); ?>"  type="text" min="3" class="form-control" data-validation="required" required>
								</div>
								
						  </div>
						</div>
			
						<div class="col-md-6">
						  <div class="form-group row margin">
							
							<label for="sel1">Celular:</label>
						   <div class="col-10">
								<input id="celular"  name="celular"   value="<?=($campos->celular); ?>" type="tel" min="3" class="form-control" required>
							</div>
							<label for="example-text-input" class="col-2 col-form-label">Clave:</label>
							<div class="col-10">
								<input id="clave" name="clave"  type="password"  value="<?=($campos->clave); ?>" min="3" class="form-control" data-validation="required" required>
							</div>
							
								
						  </div>
						  
						</div>

					</div>
					
					<div class="modal-footer">
						<input type="hidden" name="idUsuario"  value="<?=$campos->id; ?>" required="required" class="form-control">	
						<div class="col-md-8 col-md-offset-2 col-sm-12">
							<iframe name="resUpdate<?=$campos->id; ?>" src="<?=APP_PAGE_OMOLDS;?>inicio/editarInstructor" style="height: auto; max-width: 100%; width: 100%;" frameborder="0"></iframe>
						</div>    
						<button type="submit" class="btn btn-default">Actualizar</button>
					</div>
			  </div>
					
		        
		      </div>
		    </div>
			
		  </div>
	        </form>
	        
	         <!-- Modal de borrar-->
	        <form id="eliminar-alert" method="post" action="<?=APP_PAGE_OMOLDS;?>inicio/eliminaInstructor" class="contact-form form" target="resDelete<?=$campos->id; ?>">
	        <div id="modalEliminar-<?=$campos->id; ?>" class="modal fade" role="dialog">
	          <div class="modal-dialog" style="width:60%;">
	            <!-- Modal content-->
	            <div class="modal-content">
	              <div class="modal-header">
	                <button type="button" class="close" data-dismiss="modal">&times;</button>
	                <h4 class="modal-title">Borrar <?= ($campos->nombre); ?></h4>
	              </div>
	              <div class="modal-body">
	               	<p>Estas seguro de eliminar el instructor</p>
	              </div>
	              <div class="modal-footer">
					<input type="hidden" name="idCampo" id="idCampo" value="<?=$campos->id; ?>" required="required" class="form-control">
					<input type="hidden"  name="idUsuario" required="required" class="form-control" value="<?= $idUsuario ?>">
					<div class="row">
						<div class="col-md-8">
							<div class="col-md-8 col-md-offset-2 col-sm-12">
							<iframe name="resDelete<?=$campos->id; ?>" src="<?=APP_PAGE_OMOLDS;?>inicio/eliminaInstructor" style="height: auto; max-width: 100%; width: 100%;" frameborder="0"></iframe>
						   </div>
						</div>
						<div class="col-md-4">
							<div class="col-md-6"><button type="submit" class="btn btn-default">Borrar</button></div>
							<div class="col-md-6"><button type="button" class="btn btn-sm btn-primary btn-create amarillo" data-dismiss="modal">Cancelar</button></div>
						</div>
					</div>
	                
	              </div>
	            </div>
	          </div>
	        </div>
	        </form>
<?php endforeach; ?>
<?php } ?>


<style>
.margin{
	margin-left : 5px;
	margin-right : 5px;
}
</style>

 <div class="modal fade" id="nuevoUsuario" role="dialog" >
	<form  action="<?=APP_PAGE_OMOLDS;?>inicio/guardaInstructor"  method="POST" id="my_form" target="resDataInfo">
        <div class="modal-dialog" style="width:80%;">
        
          <!-- Modal content-->
          <div class="modal-content">
            <div class="modal-header">
              <button type="button" class="close" data-dismiss="modal">&times;</button>
              <h4 class="modal-title">Instructor | Información Básica</h4>
            </div>
            <div class="modal-body">
              <div class="row">
             
                <div class="col-md-6">
                  <div class="form-group row margin">
						<label for="example-text-input" class="col-2 col-form-label">Nombre:</label>
						<div class="col-10">
							<input id="nombre" name="nombre" type="text" min="3" class="form-control" data-validation="required" required>
						</div>
						
						<label for="example-text-input" class="col-2 col-form-label">Correo Electrónico:</label>
							<div class="col-10">
								<input id="email" name="email"  type="email" min="3" class="form-control" data-validation="required email" required>
						</div>
						
						<label for="example-text-input" class="col-2 col-form-label">Tipo de Instructor:</label>
							<div class="col-10">
								<input id="tipo" name="tipo"  type="text" min="3" class="form-control" data-validation="required" required>
						</div>
						
                  </div>
                </div>
    
                <div class="col-md-6">
                  <div class="form-group row margin">
					
					<label for="sel1">Celular:</label>
                   <div class="col-10">
                        <input id="celular"  name="celular"  type="tel" min="3" class="form-control" required>
                    </div>
					<label for="example-text-input" class="col-2 col-form-label">Clave:</label>
					<div class="col-10">
						<input id="clave" name="clave"  type="password" min="3" class="form-control" data-validation="required" required>
					</div>
					
						
                  </div>
                  
                </div>

             
				</div>
            <div class="modal-footer">
				<div class="row">
					<div class="col-md-8">
						<div class="col-md-8 col-md-offset-2 col-sm-12">
						<iframe name="resDataInfo" src="<?=APP_PAGE_OMOLDS;?>inicio/guardaInstructor" style="height: auto; max-width: 100%; width: 100%;" frameborder="0"></iframe>
						</div>  
					</div>
					<div class="col-md-4">
						<div class="col-md-6"> <button type="submit" class="btn btn-success" >Guardar</button></div>
						<div class="col-md-6"><button type="button" class="btn" data-dismiss="modal">Cerrar</button></div>
					</div>
				</div>
            </div>
          </div>
          
        </div>
      </div>
	 </form> 
</div>


<script>
	function actualizarIframe() {
		$("#dataclientes")[0].src = $("#dataclientes")[0].src;   
	}
</script>

 <script>
	 $( function() {
			
			 $.validate({
				modules : 'date', 
				validateOnBlur : true, // disable validation when input looses focus
				scrollToTopOnError : false // Set this property to true if you have a long form
			});
			$("#myTable").makeSearchList();
		});
	jQuery.fn.makeSearchList = function() { 	
			input = $('.buscar');	
			$(input).attr("placeholder","Search here ...");	
			var list	= $(this);
			$(input)
			.change( function () {
					var filter = $(this).val();	        
					if(filter) {	        	
					$("tr",$(list)).hide();
					  $("tr:Contains(" + filter + ")",$(list)).show();
					} else {	        	
						$("tr",$(list)).show();
					}
					return false;
				  })
				.keyup( function () {	        
					$(this).change();
				});	  
		 
				// Creamos la pseudo-funcion Contains
				jQuery.expr[":"].Contains = jQuery.expr.createPseudo(function(arg) {
					return function( elem ) {
						return jQuery(elem).text().toUpperCase().indexOf(arg.toUpperCase()) >= 0;
					};
				});
		 
		};
		
</script>
  
