<!-- navbar-->
    <header class="header">
      <div class="sticky-wrapper">
        <div role="navigation" class="navbar navbar-default">
          <div class="container">
            <div class="navbar-header">
              <button type="button" data-toggle="collapse" data-target=".navbar-collapse" class="navbar-toggle"><span class="icon-bar"></span><span class="icon-bar"></span><span class="icon-bar"></span></button><a href="#intro" class="navbar-brand scroll-to"><img src="img/imgInicio.jpg" alt=""></a>
               <a href="/login" class=""><img src="img/imgLogin.jpg" alt=""></a>
            </div>
            <div id="navigation" class="collapse navbar-collapse">
              <ul class="nav navbar-nav navbar-right">
<!--                <li class="active"><a href="#intro">INICIO</a></li>-->
                <li><a href="#about">FILOSOFÍA</a></li>
                <li><a href="#services">OMOLDS</a></li>
<!--                <li><a href="#portfolio">Portfolio</a></li>
                <li><a href="#text">Text</a></li>-->
<!--                <li><a href="#team">TALENTOS</a></li>-->
                <li><a href="#contact">CONTACTO</a></li>
              </ul>
            </div>
          </div>
        </div>
      </div>
    </header>
    <!-- /.navbar-->