<?php if(isset($promociones)){?>

<div class="tab-content" style="width:98%;">
          <div id="usuario" class="tab-pane fade in active">
            <h3>Promociones</h3>
            <p>Busque por:</p>
			<div id="inputBusqueda"></div>
            <div class="row busqueUsuario" id="inputBusqueda">
                <div class="col-md-6">
					 <label for="example-text-input" class="col-2 col-form-label">Promoción:</label>
					<input class="form-control buscar" id="busque-nombre"  type="text" />
                </div>
                <div class="col-md-6">
					<label for="example-text-input" class="col-2 col-form-label">Valor:</label>
                  <input class="form-control buscar" id="busque-cedula" type="number" />
                </div>
            </div>

            <div class="row">&nbsp;</div>
            <div class="row">
              <div class="col-md-12">
                  <div class="panel panel-default panel-table">
                    <div class="panel-heading">
                      <div class="row">
                        <div class="col col-xs-6">
                          <h3 class="panel-title">Listado promociones</h3>
                        </div>
                        <div class="col col-xs-6 text-right">
                          <button type="button" class="btn btn-sm btn-primary btn-create amarillo" data-toggle="modal" data-target="#nuevoUsuario">Nueva ++</button>
                        </div>
                      </div>
                    </div>
                    <div class="panel-body table-responsive">
                      <table class="table table-striped table-bordered table-list">
                        <thead>
                          <tr>
							<th>Promoción</th>
                            <th>Precio</th>
                            <th>Días de Duracion</th>
                            <th>activa</th>
                            <th><em class="fa fa-cog"></em></th>
                          </tr> 
                        </thead>
							<tbody id="myTable">
								<?php $totalProductos = 0;?>
								 <?php foreach($promociones as $campos): ?>
								  <tr>
									<td><?=($campos->nombre); ?></td>
									<td><?= number_format($campos->precio,0, ".", "."); ?></td>
									<td><?=($campos->diasDuracion); ?></td>
									<td><?=($campos->activo); ?>
										<?php $totalProductos ++;?>
									</td>
										 <td>
										  <a class="btn btn-info" href="#"  data-toggle="modal" data-target="#modalVer-<?=$campos->id; ?>"><i class="fa fa-eye" aria-hidden="true"></i></a>
										  <a class="btn btn-primary" href="#"  data-toggle="modal" data-target="#modalEditar-<?=$campos->id; ?>"><i class="fa fa-pencil" aria-hidden="true"></i></a>
										  <a class="btn btn-danger" href="#"  data-toggle="modal" data-target="#modalEliminar-<?=$campos->id; ?>"><i class="fa fa-trash-o" aria-hidden="true"></i></a>
									  </td>
								  </tr>
								 <?php endforeach; ?> 
                               

                              </tbody>
                      </table>
                    </div>
                    <div class="panel-footer">
                      <div class="row">
                        
                        <div class="col col-xs-4">Total de promociones <span style="color:#CC004D;">OM</span> (<span style="color:#CC004D;"><?= $totalProductos ?></span>) 
                        </div>
                        <div class="col col-xs-8">
                          <ul class="pagination hidden-xs pull-right" id="myPager">
                          </ul>
                          <ul class="pagination visible-xs pull-right">
                              <li><a href="#">«</a></li>
                              <li><a href="#">»</a></li>
                          </ul>
                        </div>
                      </div>
                    </div>
                  </div>
              </div>
            </div>
          </div>
</div>

<?php foreach($promociones as $campos): ?>

			 <!-- Modal Ver-->
	         <div id="modalVer-<?=$campos->id; ?>" class="modal fade" role="dialog">
		    <div class="modal-dialog"  style="width:80%;">
		      <!-- Modal content-->
		      <div class="modal-content">
		        <div class="modal-header">
		          <button type="button" class="close" data-dismiss="modal">&times;</button>
		          <h4 class="modal-title"><?= ($campos->nombre); ?></h4>
		        </div>

				<div class="modal-body">
				  <div class="row">
					<div class="col-md-1">&nbsp;</div>
					<div class="col-md-9">
					  <div class="form-group row margin">
						<label for="example-text-input" class="col-2 col-form-label">Promoción:</label><br>
						<label for="example-text-input" class="col-2 col-form-label"><b><?=($campos->nombre); ?></b></label><br>
					
						
						<label for="example-text-input" class="col-2 col-form-label">Precio</label><br>
						<label for="example-text-input" class="col-2 col-form-label"><b><?=($campos->precio); ?></b></label><br>
					
						
						<label for="example-text-input" class="col-2 col-form-label">Días de duración:</label><br>
						<label for="example-text-input" class="col-2 col-form-label"><b><?=($campos->diasDuracion); ?></b></label><br>
					
						
						<label for="sel1">Activa:</label><br>
						<label for="sel1"><b><?=($campos->activo); ?></label><br>
						
					  </div>
					</div>
		
					 <div class="col-md-2">&nbsp;</div>
				</div>
	
			  </div>
					
		        
		      </div>
		    </div>
			
		  </div>
	       
			
	        <!-- Modal Editar-->
	        <form id="edit-alert" method="post" action="<?=APP_PAGE_OMOLDS;?>inicio/editarPromocion" class="contact-form form" target="resUpdate<?=$campos->id; ?>">
	        <div id="modalEditar-<?=$campos->id; ?>" class="modal fade" role="dialog">
		    <div class="modal-dialog"  style="width:80%;">
		      <!-- Modal content-->
		      <div class="modal-content">
		        <div class="modal-header">
		          <button type="button" class="close" data-dismiss="modal">&times;</button>
		          <h4 class="modal-title"><?= ($campos->nombre); ?></h4>
		        </div>

				<div class="modal-body">
				  <div class="row">
					<div class="col-md-1">&nbsp;</div>
		
					<div class="col-md-9">
					  <div class="form-group row margin">
						<label for="example-text-input" class="col-2 col-form-label">Nombre Promoción:</label>
						<div class="col-10">
							<input id="nombre" name="nombre" value="<?=($campos->nombre); ?>"  type="text" min="3" class="form-control" data-validation="required" required>
						</div>
						
						<label for="example-text-input" class="col-2 col-form-label">Precio $$</label>
						<div class="col-10">
							<input id="precio"  name="precio"   value="<?=($campos->precio); ?>" type="number"  class="form-control formatear" data-validation="required number" required>
							<label class="col-2 col-form-label formatoMil" style="color:#3c763d;"></label>
						</div>
						
							<label for="example-text-input" class="col-2 col-form-label">Días de Duración:</label>
						 <div class="col-10">
							<input id="diasDuracion"  name="diasDuracion"  value="<?=($campos->diasDuracion); ?>" type="number"  class="form-control formatearDias" data-validation="required number" required>
							<label class="col-2 col-form-label formatoDias" style="color:#3c763d;"></label>
						</div>
						
					  </div>
					</div>
				
				
					 <div class="col-md-2">&nbsp;</div>
				</div>
				<div class="modal-footer">
						<input type="hidden" name="idPromocion"  value="<?=$campos->id; ?>" required="required" class="form-control">	
						<div class="col-md-8 col-md-offset-2 col-sm-12">
							<iframe name="resUpdate<?=$campos->id; ?>" src="<?=APP_PAGE_OMOLDS;?>inicio/editarPromocion" style="height: auto; max-width: 100%; width: 100%;" frameborder="0"></iframe>
						</div>    
						<button type="submit" class="btn btn-default">Actualizar</button>
					</div>
			  </div>
					
		        
		      </div>
		    </div>
			
		  </div>
	        </form>
	        
	         <!-- Modal de borrar-->
	        <form id="eliminar-alert" method="post" action="<?=APP_PAGE_OMOLDS;?>inicio/eliminaPromocion" class="contact-form form" target="resDelete<?=$campos->id; ?>">
	        <div id="modalEliminar-<?=$campos->id; ?>" class="modal fade" role="dialog">
	          <div class="modal-dialog" style="width:60%;">
	            <!-- Modal content-->
	            <div class="modal-content">
	              <div class="modal-header">
	                <button type="button" class="close" data-dismiss="modal">&times;</button>
	                <h4 class="modal-title">Borrar <?= ($campos->nombre); ?></h4>
	              </div>
	              <div class="modal-body">
	               	<p>Estas seguro de eliminar la promoción</p>
	              </div>
	              <div class="modal-footer">
	              	<input type="hidden" name="idCampo" id="idCampo" value="<?=$campos->id; ?>" required="required" class="form-control">
					<input type="hidden"  name="idUsuario" required="required" class="form-control" value="<?= $idUsuario ?>">					
					<div class="row">
						<div class="col-md-8">
							<div class="col-md-8 col-md-offset-2 col-sm-12">
							<iframe name="resDelete<?=$campos->id; ?>" src="<?=APP_PAGE_OMOLDS;?>inicio/eliminaPromocion" style="height: auto; max-width: 100%; width: 100%;" frameborder="0"></iframe>
						   </div>
						</div>
						<div class="col-md-4">
							<div class="col-md-6"><button type="submit" class="btn btn-default">Borrar</button></div>
							<div class="col-md-6"><button type="button" class="btn btn-sm btn-primary btn-create amarillo" data-dismiss="modal">Cancelar</button></div>
						</div>
					</div>
					
					
	              </div>
	            </div>
	          </div>
	        </div>
	        </form>
<?php endforeach; ?>
<?php } ?>


<style>
.margin{
	margin-left : 5px;
	margin-right : 5px;
}
</style>

 <div class="modal fade" id="nuevoUsuario" role="dialog" >
	<form  action="<?=APP_PAGE_OMOLDS;?>inicio/guardaPromocion"  method="POST" id="my_form" target="resDataInfo">
        <div class="modal-dialog" style="width:80%;">
        
          <!-- Modal content-->
          <div class="modal-content">
            <div class="modal-header">
              <button type="button" class="close" data-dismiss="modal">&times;</button>
              <h4 class="modal-title">Promoción | Información Básica</h4>
            </div>
            <div class="modal-body">
              <div class="row">
                <div class="col-md-1">&nbsp;</div>
                <div class="col-md-9">
                  <div class="form-group row margin">
                    <label for="example-text-input" class="col-2 col-form-label">Nombre Promoción:</label>
                    <div class="col-10">
                        <input id="nombre" name="nombre" type="text" min="3" class="form-control" data-validation="required" required>
                    </div>
                    
                    <label for="example-text-input" class="col-2 col-form-label">Precio $$</label>
                    <div class="col-10">
                        <input id="precio"  name="precio"  type="number"  class="form-control formatear" data-validation="required number" required>
						 <label class="col-2 col-form-label formatoMil" style="color:#3c763d;"></label>
                    </div>
					
						<label for="example-text-input" class="col-2 col-form-label">Días de Duración:</label>
                     <div class="col-10">
                        <input id="diasDuracion"  name="diasDuracion"  type="number"  class="form-control formatearDias" data-validation="required number" required>
						<label class="col-2 col-form-label formatoDias" style="color:#3c763d;"></label>
                    </div>
                    
                  </div>
                </div>
    
                
                 <div class="col-md-2">&nbsp;</div>
            </div>
            <div class="modal-footer">
			  <div class="row">
					<div class="col-md-8">
						<div class="col-md-8 col-md-offset-2 col-sm-12">
							<iframe name="resDataInfo" src="<?=APP_PAGE_OMOLDS;?>inicio/guardaPromocion" style="height: auto; max-width: 100%; width: 100%;" frameborder="0"></iframe>
						 </div>  
					</div>
					<div class="col-md-4">
						<div class="col-md-6"> <button type="submit" class="btn btn-success" >Guardar</button></div>
						<div class="col-md-6"><button type="button" class="btn" data-dismiss="modal">Cerrar</button></div>
					</div>
				</div>
            </div>
          </div>
          
        </div>
      </div>
	 </form> 
</div>


<script>
	function actualizarIframe() {
		$("#dataclientes")[0].src = $("#dataclientes")[0].src;   
	}
</script>

 <script>
	 $( function() {
			$.datepicker.setDefaults({
				yearRange: '-100:+0',
				onSelect: function (date) {
					fecha = new Date(date);
					hoy = new Date();
					ed = parseInt((hoy - fecha)/365/24/60/60/1000);
					alert("¡Tiene " + ed + " años!");
				}
			});
			
			 $.validate({
				modules : 'date', 
				validateOnBlur : true, // disable validation when input looses focus
				scrollToTopOnError : false // Set this property to true if you have a long form
			});
			
			$("#myTable").makeSearchList();
			
			/*formateamo el numero en miles*/
			$('.formatear').keyup( function () {	        
					 mil = format($(this).val());
					$('.formatoMil').html('El valor a pagar es de $'+mil);
			});	
			
			/*formateamo los dias de duracion*/
			/*$('.formatearDias').keyup( function () {	        
					 dias = format($(this).val());
					 fechaMasDias = calcularFechaSumandoDias(dias);
					 diferencia = dateDiff2(FechaActual(),fechaMasDias,'YYY-M-D','-',true,false);
					$('.formatoDias').html('Son '+diferencia);
			});	*/
				
			$('.modal').on('hidden.bs.modal', function () {
				$('.formatoMil').html('');
				$('.formatoDias').html('');
			})	;
			
		});
	
		jQuery.fn.makeSearchList = function() { 	
			input = $('.buscar');	
			$(input).attr("placeholder","Search here ...");	
			var list	= $(this);
			$(input)
			.change( function () {
					var filter = $(this).val();	        
					if(filter) {	        	
					$("tr",$(list)).hide();
					  $("tr:Contains(" + filter + ")",$(list)).show();
					} else {	        	
						$("tr",$(list)).show();
					}
					return false;
				  })
				.keyup( function () {	        
					$(this).change();
				});	  
		 
				// Creamos la pseudo-funcion Contains
				jQuery.expr[":"].Contains = jQuery.expr.createPseudo(function(arg) {
					return function( elem ) {
						return jQuery(elem).text().toUpperCase().indexOf(arg.toUpperCase()) >= 0;
					};
				});
				
				
		 
		};
		
		function format(num){
			if(!isNaN(num)){
			num = num.toString().split('').reverse().join('').replace(/(?=\d*\.?)(\d{3})/g,'$1.');
			num = num.split('').reverse().join('').replace(/^[\.]/,'');
			valor = num;
			}else{ 
				valor = 'Solo se permiten numeros';
			}
			return valor;
		}
		
		function FechaActual(){
			var hoy = new Date();
			var dd = hoy.getDate();
			var mm = hoy.getMonth()+1; //hoy es 0!
			var yyyy = hoy.getFullYear();

			if(dd<10) {
				dd='0'+dd
			} 

			if(mm<10) {
				mm='0'+mm
			} 

			hoy = yyyy+'-'+mm+'-'+dd;
			return hoy;
		}
		
		function calcularFechaSumandoDias(tiempo){
			var fecha = new Date(),
				dia = fecha.getDate(),
				mes = fecha.getMonth() + 1,
				anio = fecha.getFullYear(),
				addTime = tiempo * 86400; //Tiempo en segundos
			
			fecha.setSeconds(addTime); //Añado el tiempo
			
			getMonth = fecha.getMonth() + 1;	
			getDate = fecha.getDate();	
			if(getDate<10) {
				getDate='0'+getDate
			} 

			if(getMonth<10) {
				getMonth='0'+getMonth
			} 
			
			return  fecha.getFullYear() + "-" + getMonth + "-" + getDate;
		};
		

		
		
</script>
  
