<?php if(isset($gastos)){?>

<div class="tab-content" style="width:98%;">
          <div id="usuario" class="tab-pane fade in active">
            <h3>Gastos</h3>
            <p>Busque por:</p>
            <div class="row busqueUsuario" id="inputBusqueda">
                <div class="col-md-12">
					
					<input class="form-control buscar" id="busque-nombre"  type="text" />
                </div>
                
            </div>

            <div class="row">&nbsp;</div>
            <div class="row">
              <div class="col-md-12">
                  <div class="panel panel-default panel-table">
                    <div class="panel-heading">
                      <div class="row">
                        <div class="col col-xs-6">
                          <h3 class="panel-title">Listado de Gastos</h3>
                        </div>
                        <div class="col col-xs-6 text-right">
                          <button type="button" class="btn btn-sm btn-primary btn-create amarillo" data-toggle="modal" data-target="#filtroFecha">Filtro</button>
                          <button type="button" class="btn btn-sm btn-primary btn-create amarillo" data-toggle="modal" data-target="#nuevoUsuario">Nuevo ++</button>
                        </div>
                      </div>
                    </div>
                    <div class="panel-body table-responsive">
                      <table class="table table-striped table-bordered table-list">
                        <thead>
                          <tr>
							<th>Motivo</th>
                            <th>Valor</th>
                            <th>Fecha del gasto</th>
                            <th><em class="fa fa-cog"></em></th>
                          </tr> 
                        </thead>
							<tbody id="myTable">
								<?php $totalGatos = 0;?>
								 <?php foreach($gastos as $campos): ?>
								  <tr>
									<td><?=($campos->motivo); ?></td>
									<td><?=($campos->precio); ?></td>
									<td><?=($campos->fechaGasto); ?>
										<?php $totalGatos += $campos->precio; ?>
									</td>
										 <td>
										  <a class="btn btn-info" href="#"  data-toggle="modal" data-target="#modalVer-<?=$campos->id; ?>"><i class="fa fa-eye" aria-hidden="true"></i></a>
										  <a class="btn btn-primary" href="#"  data-toggle="modal" data-target="#modalEditar-<?=$campos->id; ?>"><i class="fa fa-pencil" aria-hidden="true"></i></a>
										  <a class="btn btn-danger" href="#"  data-toggle="modal" data-target="#modalEliminar-<?=$campos->id; ?>"><i class="fa fa-trash-o" aria-hidden="true"></i></a>
									  </td>
								  </tr>
								 <?php endforeach; ?> 
                               

                              </tbody>
                      </table>
                    </div>
                    <div class="panel-footer">
                      <div class="row">
                        
                        <div class="col col-xs-4">Total de Gatos <span style="color:#CC004D;">OM</span> (<span style="color:#CC004D;"><?= $totalGatos ?></span>) 
                        </div>
                        <div class="col col-xs-8">
                          <ul class="pagination hidden-xs pull-right" id="myPager">
                          </ul>
                          <ul class="pagination visible-xs pull-right">
                              <li><a href="#">«</a></li>
                              <li><a href="#">»</a></li>
                          </ul>
                        </div>
                      </div>
                    </div>
                  </div>
              </div>
            </div>
          </div>
</div>

<?php foreach($gastos as $campos): ?>

			 <!-- Modal Ver-->
	         <div id="modalVer-<?=$campos->id; ?>" class="modal fade" role="dialog">
		    <div class="modal-dialog"  style="width:50%;">
		      <!-- Modal content-->
		      <div class="modal-content">
		        <div class="modal-header">
		          <button type="button" class="close" data-dismiss="modal">&times;</button>
		          <h4 class="modal-title"><?= ($campos->fechaGasto); ?></h4>
		        </div>

				<div class="modal-body">
				  <div class="row">

					
						<div class="col-md-12">
						  <div class="form-group row margin">
								<label for="example-text-input" class="col-2 col-form-label">Motivo:</label>
								<label for="example-text-input" class="col-2 col-form-label"><b><?=($campos->motivo); ?></b></label>
								<br>
								
								<label for="example-text-input" class="col-2 col-form-label">Valor del gasto:</label>
								<label for="example-text-input" class="col-2 col-form-label"><b><?=($campos->precio); ?></b></label>
								<br>
								
								<label for="example-text-input" class="col-2 col-form-label">fecha del gasto:</label>
								<label for="example-text-input" class="col-2 col-form-label"><b><?=($campos->fechaGasto); ?></b></label>
								<br>	
								
								<br>
						  </div>
						</div>
			
				</div>
	
			  </div>
					
		        
		      </div>
		    </div>
			
		  </div>
	       
			
	        <!-- Modal Editar-->
	        <form id="edit-alert" method="post" action="<?=APP_PAGE_OMOLDS;?>inicio/editarGasto" class="contact-form form" target="resUpdate<?=$campos->id; ?>">
	        <div id="modalEditar-<?=$campos->id; ?>" class="modal fade" role="dialog">
		    <div class="modal-dialog"  style="width:80%;">
		      <!-- Modal content-->
		      <div class="modal-content">
		        <div class="modal-header">
		          <button type="button" class="close" data-dismiss="modal">&times;</button>
		          <h4 class="modal-title"><?= ($campos->fechaGasto); ?></h4>
		        </div>

				<div class="modal-body">
					<div class="row">
					
						<div class="col-md-12">
						  <div class="form-group row margin">
								<label for="example-text-input" class="col-2 col-form-label">Motivo:</label>
								<div class="col-10">
									<input id="motivo" name="motivo"  value="<?=($campos->motivo); ?>" type="text" min="3" class="form-control" data-validation="required" required>
								</div>
								
								<label for="example-text-input" class="col-2 col-form-label">Valor del gasto:</label>
									<div class="col-10">
										<input id="precio" name="precio"   value="<?=($campos->precio); ?>" type="number"  class="form-control formatear" data-validation="required number" required>
										<label class="col-2 col-form-label formatoMil" style="color:#3c763d;"></label>
								</div>
								
								<label for="example-text-input" class="col-2 col-form-label">Fecha del gasto:</label>
								<div class="col-10">
									 <input  name="fechaGasto" value="<?=($campos->fechaGasto); ?>"  type="text"  class="form-control datepicker" data-validation="required" data-validation-format="yyyy/mm/dd"  required>
								</div>
							
						  </div>
						</div>
			
						

					</div>
					
					<div class="modal-footer">
						<input type="hidden" name="idGasto"  value="<?=$campos->id; ?>" required="required" class="form-control">	
						<div class="col-md-8 col-md-offset-2 col-sm-12">
							<iframe name="resUpdate<?=$campos->id; ?>" src="<?=APP_PAGE_OMOLDS;?>inicio/editarGasto" style="height: auto; max-width: 100%; width: 100%;" frameborder="0"></iframe>
						</div>    
						<button type="submit" class="btn btn-default">Actualizar</button>
					</div>
			  </div>
					
		        
		      </div>
		    </div>
			
		  </div>
	        </form>
	        
	         <!-- Modal de borrar-->
	        <form id="eliminar-alert" method="post" action="<?=APP_PAGE_OMOLDS;?>inicio/eliminaGasto" class="contact-form form" target="resDelete<?=$campos->id; ?>">
	        <div id="modalEliminar-<?=$campos->id; ?>" class="modal fade" role="dialog">
	          <div class="modal-dialog" style="width:60%;">
	            <!-- Modal content-->
	            <div class="modal-content">
	              <div class="modal-header">
	                <button type="button" class="close" data-dismiss="modal">&times;</button>
	                <h4 class="modal-title">Borrar <?= ($campos->fechaGasto); ?></h4>
	              </div>
	              <div class="modal-body">
	               	<p>Estas seguro de eliminar el gasto</p>
	              </div>
	              <div class="modal-footer">
					<input type="hidden" name="idCampo" id="idCampo" value="<?=$campos->id; ?>" required="required" class="form-control">
					<input type="hidden"  name="idUsuario" required="required" class="form-control" value="<?= $idUsuario ?>">
					<div class="row">
						<div class="col-md-8">
							<div class="col-md-8 col-md-offset-2 col-sm-12">
							<iframe name="resDelete<?=$campos->id; ?>" src="<?=APP_PAGE_OMOLDS;?>inicio/eliminaGasto" style="height: auto; max-width: 100%; width: 100%;" frameborder="0"></iframe>
						   </div>
						</div>
						<div class="col-md-4">
							<div class="col-md-6"><button type="submit" class="btn btn-default">Borrar</button></div>
							<div class="col-md-6"><button type="button" class="btn btn-sm btn-primary btn-create amarillo" data-dismiss="modal">Cancelar</button></div>
						</div>
					</div>
	                
	              </div>
	            </div>
	          </div>
	        </div>
	        </form>
<?php endforeach; ?>
<?php } ?>


<style>
.margin{
	margin-left : 5px;
	margin-right : 5px;
}
</style>

 <div class="modal fade" id="nuevoUsuario" role="dialog" >
	<form  action="<?=APP_PAGE_OMOLDS;?>inicio/guardaGasto"  method="POST" id="my_form" target="resDataInfo">
        <div class="modal-dialog" style="width:80%;">
        
          <!-- Modal content-->
          <div class="modal-content">
            <div class="modal-header">
              <button type="button" class="close" data-dismiss="modal">&times;</button>
              <h4 class="modal-title">Gasto | Información Básica</h4>
            </div>
            <div class="modal-body">
              <div class="row">
             
                <div class="col-md-12">
                  <div class="form-group row margin">
						<label for="example-text-input" class="col-2 col-form-label">Motivo:</label>
						<div class="col-10">
							<input id="motivo" name="motivo" type="text" min="3" class="form-control" data-validation="required" required>
						</div>
						
						<label for="example-text-input" class="col-2 col-form-label">Valor del gasto:</label>
							<div class="col-10">
								<input id="precio" name="precio"  type="number"  class="form-control formatear" data-validation="required number" required>
								<label class="col-2 col-form-label formatoMil" style="color:#3c763d;"></label>
						</div>
						
						<label for="example-text-input" class="col-2 col-form-label">Fecha del gasto:</label>
							<div class="col-10">
								 <input id="fechaGastoN" name="fechaGasto"  type="text"  class="form-control datepicker" data-validation="required" data-validation-format="yyyy/mm/dd"  required>
						</div>
						
                  </div>
                </div>
             
				</div>
            <div class="modal-footer">
				<div class="row">
					<div class="col-md-8">
						<div class="col-md-8 col-md-offset-2 col-sm-12">
						<iframe name="resDataInfo" src="<?=APP_PAGE_OMOLDS;?>inicio/guardaGasto" style="height: auto; max-width: 100%; width: 100%;" frameborder="0"></iframe>
						</div>  
					</div>
					<div class="col-md-4">
						<div class="col-md-6"> <button type="submit" class="btn btn-success" >Guardar</button></div>
						<div class="col-md-6"><button type="button" class="btn" data-dismiss="modal">Cerrar</button></div>
					</div>
				</div>
            </div>
          </div>
          
        </div>
      </div>
	 </form> 
</div>



 <div class="modal fade" id="filtroFecha" role="dialog" >
        <div class="modal-dialog" >
        
          <!-- Modal content-->
          <div class="modal-content">
            <div class="modal-header">
              <button type="button" class="close" data-dismiss="modal">&times;</button>
              <h4 class="modal-title">Filtrar gasto por mes y año</h4>
            </div>
            <div class="modal-body">
              <div class="row">
             
                <div class="col-md-12">
          	
						<div class="col-6">
							<label for="example-text-input" class="col-2 col-form-label">Año:</label>
							<select  id="ano-filtro">
									<option value="0">A&ntilde;o..</option>
									<option value="<?= $anioActual ?>" selected ><?= $anioActual ?></option>
									<option value="<?= $anio ?>" selected ><?= $anio ?></option>
									<option value="<?= $anio -1 ?>"  ><?= $anio -1 ?></option>
									<option value="<?= $anio -2 ?>"  ><?= $anio-2 ?></option>
									<option value="<?= $anio-3 ?>"  ><?= $anio-3 ?></option>
									<option value="<?= $anio-4 ?>"  ><?= $anio-4 ?></option>
									<option value="<?= $anio-5 ?>"  ><?= $anio-5 ?></option>
									<option value="<?= $anio-6 ?>"  ><?= $anio-6 ?></option>
									<option value="<?= $anio-7 ?>"  ><?= $anio-7 ?></option>
									<option value="<?= $anio-8 ?>"  ><?= $anio-8 ?></option>
									<option value="<?= $anio-9 ?>"  ><?= $anio-9 ?></option>
									<option value="<?= $anio-10 ?>"  ><?= $anio-10 ?></option>
							 </select>
						</div>
						
						
						<div class="col-6">
							<label for="example-text-input" class="col-2 col-form-label">Mes:</label>
								<select  id="mes-filtro">
									<option value="0">Mes..</option>
										<option value="01" <?php if($mes == '01'){ echo 'selected'; } ?>>Enero</option>
										<option value="02" <?php if ($mes == '02'){ echo  'selected';} ?>>Febrero</option>
										<option value="03" <?php if ($mes == '03'){ echo 'selected';}?>>Marzo</option>
										<option value="04" <?php if ($mes == '04'){ echo  'selected';} ?>>Abril</option>
										<option value="05" <?php if ($mes == '05'){ echo  'selected';} ?>>Mayo</option>
										<option value="06" <?php if ($mes == '06'){ echo  'selected';} ?>>Junio</option>
										<option value="07" <?php if ($mes == '07'){ echo  'selected';} ?>>Julio</option>
										<option value="08" <?php if ($mes == '08'){ echo  'selected';} ?>>Agosto</option>
										<option value="09" <?php if ($mes == '09'){ echo  'selected';} ?>>Septiembre</option>
										<option value="10" <?php if ($mes == '10'){ echo  'selected';} ?>>Octubre</option>
										<option value="11" <?php if ($mes == '11'){ echo  'selected';} ?>>Noviembre</option>
										<option value="12" <?php if ($mes == '12'){ echo  'selected';} ?>>Diciembre</option>
							  </select>
						</div>
						
						
						
                  
                </div>
             
				</div>
          </div>
          
        </div>
      </div>
</div>


<script>
	function actualizarIframe() {
		$("#dataclientes")[0].src = $("#dataclientes")[0].src;   
	}
</script>

 <script>
	 $( function() {
		 
			$( "#ano-filtro" ).change(function () {
				$( "#ano-filtro  option:selected" ).each(function() {
					window.location = "<?=APP_PAGE_OMOLDS;?>inicio/listadoGastos/"+$( this ).val();
				});
				return false;
			});
			
			$( "#mes-filtro" ).change(function () {
				$( "#mes-filtro  option:selected" ).each(function() {
					window.location = "<?=APP_PAGE_OMOLDS;?>inicio/listadoGastos/"+$("#ano-filtro  option:selected").val()+"/"+$( this ).val();
				});
				return false;
			});
					
			
			$.datepicker.setDefaults({
				yearRange: '-100:+0'
			});
			
			 $.validate({
				modules : 'date', 
				validateOnBlur : true, // disable validation when input looses focus
				scrollToTopOnError : false // Set this property to true if you have a long form
			});
			
			/*formateamo el numero en miles*/
			$('.formatear').keyup( function () {	        
					 mil = format($(this).val());
					$('.formatoMil').html('El valor del gasto es de $'+mil);
			});	
			
			$("#myTable").makeSearchList();
		});
		
		function format(num){
			if(!isNaN(num)){
			num = num.toString().split('').reverse().join('').replace(/(?=\d*\.?)(\d{3})/g,'$1.');
			num = num.split('').reverse().join('').replace(/^[\.]/,'');
			valor = num;
			}else{ 
				valor = 'Solo se permiten numeros';
			}
			return valor;
		}
		
	jQuery.fn.makeSearchList = function() { 	
			input = $('.buscar');	
			$(input).attr("placeholder","Search here ...");	
			var list	= $(this);
			$(input)
			.change( function () {
					var filter = $(this).val();	        
					if(filter) {	        	
					$("tr",$(list)).hide();
					  $("tr:Contains(" + filter + ")",$(list)).show();
					} else {	        	
						$("tr",$(list)).show();
					}
					return false;
				  })
				.keyup( function () {	        
					$(this).change();
				});	  
		 
				// Creamos la pseudo-funcion Contains
				jQuery.expr[":"].Contains = jQuery.expr.createPseudo(function(arg) {
					return function( elem ) {
						return jQuery(elem).text().toUpperCase().indexOf(arg.toUpperCase()) >= 0;
					};
				});
		 
		};
		
</script>
  
